parameters:
#    beosmappermain.example.class: beosmapper\mainBundle\Example

services:
#    beosmappermain.example:
#        class: %beosmappermain.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
